package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"time"

	"appointments/domain/entities"
	"appointments/transport/graphql/generated"
	"appointments/transport/graphql/model"
)

// — DateTime resolvers —
// gqlgen no conoce time.Time nativamente, estos métodos convierten
// los campos DateTime del schema a string ISO 8601 para la respuesta JSON.

func (r *citaResolver) FechaHora(ctx context.Context, obj *entities.Cita) (string, error) {
	return obj.FechaHora.Format(time.RFC3339), nil
}

func (r *citaResolver) CreatedAt(ctx context.Context, obj *entities.Cita) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

func (r *pacienteResolver) FechaNacimiento(ctx context.Context, obj *entities.Paciente) (string, error) {
	return obj.FechaNacimiento.Format(time.RFC3339), nil
}

func (r *pacienteResolver) CreatedAt(ctx context.Context, obj *entities.Paciente) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

func (r *doctorResolver) CreatedAt(ctx context.Context, obj *entities.Doctor) (string, error) {
	return obj.CreatedAt.Format(time.RFC3339), nil
}

// — Relaciones —
// gqlgen necesita resolvers explícitos para campos que son structs embebidos,
// porque no puede asumir que ya están cargados en el objeto padre.

func (r *citaResolver) Paciente(ctx context.Context, obj *entities.Cita) (*entities.Paciente, error) {
	return &obj.PacienteAsignado, nil
}

func (r *citaResolver) Doctor(ctx context.Context, obj *entities.Cita) (*entities.Doctor, error) {
	return &obj.DoctorAsignado, nil
}

// — Mutations —

func (r *mutationResolver) RegistrarPaciente(ctx context.Context, input model.RegistrarPacienteInput) (*entities.Paciente, error) {
	fechaNacimiento, err := time.Parse(time.RFC3339, input.FechaNacimiento)
	if err != nil {
		return nil, err
	}

	paciente, err := r.PacienteService.Registrar(entities.Paciente{
		Nombre:          input.Nombre,
		Email:           input.Email,
		Telefono:        input.Telefono,
		FechaNacimiento: fechaNacimiento,
	})
	if err != nil {
		return nil, err
	}

	return &paciente, nil
}

func (r *mutationResolver) RegistrarDoctor(ctx context.Context, input model.RegistrarDoctorInput) (*entities.Doctor, error) {
	doctor, err := r.DoctorService.Registrar(entities.Doctor{
		Nombre:       input.Nombre,
		Email:        input.Email,
		Especialidad: input.Especialidad,
	})
	if err != nil {
		return nil, err
	}

	return &doctor, nil
}

func (r *mutationResolver) AgendarCita(ctx context.Context, input model.AgendarCitaInput) (*entities.Cita, error) {
	fechaHora, err := time.Parse(time.RFC3339, input.FechaHora)
	if err != nil {
		return nil, err
	}

	cita, err := r.CitaService.Agendar(entities.Cita{
		Motivo:           input.Motivo,
		FechaHora:        fechaHora,
		PacienteAsignado: entities.Paciente{ID: input.PacienteID},
		DoctorAsignado:   entities.Doctor{ID: input.DoctorID},
	})
	if err != nil {
		return nil, err
	}

	return &cita, nil
}

func (r *mutationResolver) ActualizarEstadoCita(ctx context.Context, input model.ActualizarEstadoInput) (*entities.Cita, error) {
	cita, err := r.CitaService.ActualizarEstado(input.ID, entities.EstadoCita(input.Estado))
	if err != nil {
		return nil, err
	}

	return &cita, nil
}

func (r *mutationResolver) CancelarCita(ctx context.Context, id int) (*entities.Cita, error) {
	cita, err := r.CitaService.Cancelar(id)
	if err != nil {
		return nil, err
	}

	return &cita, nil
}

// — Queries —

func (r *queryResolver) Pacientes(ctx context.Context) ([]*entities.Paciente, error) {
	pacientes, err := r.PacienteService.BuscarTodos()
	if err != nil {
		return nil, err
	}

	result := make([]*entities.Paciente, len(pacientes))
	for i := range pacientes {
		result[i] = &pacientes[i]
	}

	return result, nil
}

func (r *queryResolver) Paciente(ctx context.Context, id int) (*entities.Paciente, error) {
	paciente, err := r.PacienteService.BuscarPorID(id)
	if err != nil {
		return nil, err
	}

	return &paciente, nil
}

func (r *queryResolver) Doctores(ctx context.Context) ([]*entities.Doctor, error) {
	doctores, err := r.DoctorService.BuscarTodos()
	if err != nil {
		return nil, err
	}

	result := make([]*entities.Doctor, len(doctores))
	for i := range doctores {
		result[i] = &doctores[i]
	}

	return result, nil
}

func (r *queryResolver) Doctor(ctx context.Context, id int) (*entities.Doctor, error) {
	doctor, err := r.DoctorService.BuscarPorID(id)
	if err != nil {
		return nil, err
	}

	return &doctor, nil
}

func (r *queryResolver) CitasPorPaciente(ctx context.Context, pacienteID int) ([]*entities.Cita, error) {
	citas, err := r.CitaService.BuscarPorPaciente(pacienteID)
	if err != nil {
		return nil, err
	}

	result := make([]*entities.Cita, len(citas))
	for i := range citas {
		result[i] = &citas[i]
	}

	return result, nil
}

func (r *queryResolver) CitasPorDoctor(ctx context.Context, doctorID int) ([]*entities.Cita, error) {
	citas, err := r.CitaService.BuscarPorDoctor(doctorID)
	if err != nil {
		return nil, err
	}

	result := make([]*entities.Cita, len(citas))
	for i := range citas {
		result[i] = &citas[i]
	}

	return result, nil
}

// — Registros de resolvers (generados por gqlgen, no tocar) —

func (r *Resolver) Cita() generated.CitaResolver       { return &citaResolver{r} }
func (r *Resolver) Doctor() generated.DoctorResolver   { return &doctorResolver{r} }
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }
func (r *Resolver) Paciente() generated.PacienteResolver { return &pacienteResolver{r} }
func (r *Resolver) Query() generated.QueryResolver     { return &queryResolver{r} }

type citaResolver struct{ *Resolver }
type doctorResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type pacienteResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
