// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"appointments/domain/entities"
)

type ActualizarEstadoInput struct {
	ID     int                 `json:"id"`
	Estado entities.EstadoCita `json:"estado"`
}

type AgendarCitaInput struct {
	PacienteID int    `json:"pacienteID"`
	DoctorID   int    `json:"doctorID"`
	Motivo     string `json:"motivo"`
	FechaHora  string `json:"fechaHora"`
}

type Mutation struct {
}

type Query struct {
}

type RegistrarDoctorInput struct {
	Nombre       string `json:"nombre"`
	Especialidad string `json:"especialidad"`
	Email        string `json:"email"`
}

type RegistrarPacienteInput struct {
	Nombre          string `json:"nombre"`
	Email           string `json:"email"`
	Telefono        string `json:"telefono"`
	FechaNacimiento string `json:"fechaNacimiento"`
}
